### PR TITLE
Skip access token check for PR verification

### LINKED ISSUE #151: Skip access token verification for PR checks
Currently, the pr checks are failing because access token verification happens regardless of commits or PRs

### PR DESCRIPTION
**Pull request by samiyaakhtar**
Currently, PR verifications are failing because the check for access tokens happens regardless of commit or PR. Closes #151

### CODE REVIEW

File: gitops/azure-devops/build.sh [hunk 1]
```diff
@@ -163,7 +167,7 @@ function unit_test() {
     echo "Sourcing for unit test..."
 }
 
-function verify() {
+function pr_verify() {
```
Comment (andrebriggs) [inline gitops/azure-devops/build.sh]: @samiyaakhtar can we be more explicit and say verify_pull_request()?

File: gitops/azure-devops/build.sh [hunk 2]
```diff
@@ -175,7 +179,8 @@ function verify() {
 
 # Run functions
 function verify_and_push() {
```
Comment (andrebriggs) [inline gitops/azure-devops/build.sh]: I suppose we could be more explicit here to. Maybe "verify_pull_request_and_merge" Thoughts?
