### PR TITLE
PreReqs Fix for common func 

### LINKED ISSUE #1239: setup_azure_cli.sh generates an error message but completes successfully.
`sudo ./setup_azure_cli.sh`
Script produces the following message:

/c/repos/EpiServer/bedrockinwsl/bedrock/tools/prereqs/ common_funcs.sh: line 82: + : syntax error: operand expected (error token is "+ ")]”  

this repros on WSL, did not test this command on other environments

### PR DESCRIPTION
**Pull request by NathanielRose**
- Jim fix for - ` line 82: + : syntax error: operand expected (error token is "+ ")]”`
- Closes #1239 
- Adding Build badge

### CODE REVIEW

File: tools/prereqs/setup_terraform.sh [hunk 1]
```diff
@@ -30,8 +30,10 @@ cd $tmp_dir
 ostype=`os_type`
 if [ "$ostype" == "linux" ]; then
     arch="linux_amd64"
+    sudo apt-get install unzip
 elif [ "$ostype" == "macos" ]; then
     arch="darwin_amd64"
+    brew install unzip
```
Comment (jmspring) [inline tools/prereqs/setup_terraform.sh]: Makes an assumption brew is installed.  Also, unzip comes preinstalled on every Mac I have ever had.
